/** Static marketing / UX helpers (not API fallbacks). */

export const DUMMY_GENERATIONS = [
  {
    id: 'gen_01',
    type: 'image',
    prompt: 'A futuristic cityscape at dusk with holographic advertisements and flying vehicles, photorealistic, 8K',
    status: 'completed',
    media_url:
      'https://images.unsplash.com/photo-1525373698358-041e3a460346?w=600&auto=format&fit=crop&q=60',
    thumbnail_url: 'https://images.unsplash.com/photo-1537498425277-c283d32ef9db?w=400',
    credits_used: 10,
    api_provider: 'openai',
    created_at: '2026-05-31T08:30:00Z',
    parameters: { size: '1024x1024', quality: 'hd', style: 'vivid' },
  },
  {
    id: 'gen_02',
    type: 'image',
    prompt: 'Abstract digital art, flowing neon light trails on dark background, ultra detailed',
    status: 'completed',
    media_url:
      'https://plus.unsplash.com/premium_photo-1669814666151-c254da68476f?w=600&auto=format&fit=crop&q=60',
    thumbnail_url: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=400',
    credits_used: 5,
    api_provider: 'openai',
    created_at: '2026-05-30T14:00:00Z',
    parameters: { size: '1024x1024', quality: 'standard', style: 'natural' },
  },
  {
    id: 'gen_03',
    type: 'video',
    prompt: 'Slow motion ocean waves at golden hour, cinematic, 4K',
    status: 'completed',
    media_url: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=400',
    credits_used: 25,
    api_provider: 'kling',
    created_at: '2026-05-29T09:15:00Z',
    parameters: { duration: '5s', aspect_ratio: '16:9' },
  },
  {
    id: 'gen_04',
    type: 'image',
    prompt: 'Minimalist product shot of a luxury watch on black marble, studio lighting',
    status: 'completed',
    media_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
    thumbnail_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
    credits_used: 10,
    api_provider: 'openai',
    created_at: '2026-05-28T11:00:00Z',
    parameters: { size: '1024x1024', quality: 'hd', style: 'natural' },
  },
  {
    id: 'gen_05',
    type: 'video',
    prompt: 'Time-lapse of clouds over mountain peaks, dramatic, cinematic',
    status: 'failed',
    media_url: null,
    thumbnail_url: null,
    credits_used: 0,
    credits_refunded: true,
    api_provider: 'kling',
    created_at: '2026-05-29T09:10:00Z',
    parameters: { duration: '5s', aspect_ratio: '16:9' },
  },
  {
    id: 'gen_06',
    type: 'image',
    prompt: 'Portrait of a cyberpunk hacker, neon-lit background, cinematic, shallow depth of field',
    status: 'processing',
    media_url: null,
    thumbnail_url: null,
    credits_used: 10,
    api_provider: 'openai',
    created_at: '2026-05-31T09:45:00Z',
    parameters: { size: '1792x1024', quality: 'hd', style: 'vivid' },
  },
] as const;

export const SUGGESTION_PROMPTS = [
  'Futuristic cityscape at dusk, neon lights, cinematic',
  'Minimalist product shot on black marble, studio lighting',
  'Abstract fluid art, electric colors on dark background',
  'Portrait in golden hour, shallow depth of field',
  'Aerial view of mountain range, drone shot, 8K',
  'Luxury interior design, warm lighting, modern aesthetic',
] as const;
